### PR TITLE
Move building to GitHub Actions

### PR DESCRIPTION
**Pull request by okalachev**
The latest release build in Travis CI didn't work, so there is no release assets. Building the project from sources is not so easy.

This PR moves building to GitHub Actions, including uploading build artifacts to releases.

Also, note, that shown version for release is not get updated automatically, so it should be updated manually [here](https://github.com/PX4/FlightPlot/blob/master/build.xml#L51) and [here](https://github.com/PX4/FlightPlot/blob/master/src/me/drton/flightplot/FlightPlot.java#L77). Or some automatisation should be added, see https://stackoverflow.com/questions/2974106/how-to-lookup-the-latest-git-commit-hash-from-an-ant-build-script.

### CODE REVIEW

**Review by bkueng — APPROVED** [review]
Thanks, did you test this already?

**Comment by okalachev** [comment]
On my MacBook with macOS Monterey and OpenJDK installed, I am able to run the `.jar`-file without any issues.

However, I cannot run the `.app`, seeing this:

Screenshot 2022-04-26 at 10 30 58

So, maybe the `.app` should not be published, or this problem should be investigated later.

I guess this is not related to Actions transfer.

**Comment by bkueng** [comment]
Yes we can look at this independently.

**Comment by okalachev** [comment]
@bkueng, I guess you have to enable Actions somewhere in the settings, so the 'Actions' tab would appear and workflows begin running.

**Comment by bkueng** [comment]
Indeed, it tells me `This setting has been disabled by organization administrators.` @dagar do you have the admin rights to enable?
I noticed the same for https://github.com/PX4/flight_review/settings/actions.

**Comment by dagar** [comment]
Can you try now? It was changed at the org level to be opt in per repo rather than on by default after PX4-Autopilot builds were getting stuck queued all day. I think the free build resources were a bit more generous initially.

**Comment by bkueng** [comment]
It's working, at least for flight_review, thanks.

**Pull request merged**
