### PR TITLE
remove the type of the elements of this combo box

### PR DESCRIPTION
**Pull request by stmoon**
When I compile flightplot, I have some problems with this statement like below
"javax.swing.JComboBox does not take parameters"

In order to solve this problem, I remove the type of the elements of this combo box.

```
stmoon:~/Project/PX4/FlightPlot$ ant
Buildfile: /home/stmoon/Project/PX4/FlightPlot/build.xml

make_dirs:
    [mkdir] Created dir: /home/stmoon/Project/PX4/FlightPlot/out/production/FlightPlot

compile:
   [javac2] Compiling 108 source files to /home/stmoon/Project/PX4/FlightPlot/out/production/FlightPlot
   [javac2] /home/stmoon/Project/PX4/FlightPlot/src/me/drton/flightplot/FlightPlot.java:96: type javax.swing.JComboBox does not take parameters
   [javac2]     private JComboBox<Preset> presetComboBox;
   [javac2]                      ^
   [javac2] Note: Some input files use unchecked or unsafe operations.
   [javac2] Note: Recompile with -Xlint:unchecked for details.
   [javac2] 1 error

BUILD FAILED
/home/stmoon/Project/PX4/FlightPlot/build.xml:24: Compile failed; see the compiler error output for details.

Total time: 1 second
```

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I'm not sure we want to merge this - you have this issue because you use Java 1.6, which is very, very, very old. You should have 1.7 or merely 1.8 on a modern system - what is the OS you are running?

**Comment by stmoon** [comment]
Actually, this problem happen on version 1.8 and 1.9 in the same way. I use Ubuntu 16.04.2 LTS

**Comment by LorenzMeier** [comment]
Got it. That's a very good reason to fix!

**Comment by stmoon** [comment]
In addition, the README says the building requirement version is Java 6 or newer.

**Pull request merged**
